# Generated by Django 4.0.5 on 2022-06-15 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modification date')),
                ('service_area_name', models.CharField(max_length=50, unique=True, verbose_name='service area name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('geoinformation', models.JSONField()),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to='polygon.provider', verbose_name='provider foreign key')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
